language: ruby
cache: bundler

script: "bundle exec rake"

rvm:
  - 1.9.3
  - 2.0.0

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - bundle exec rake app:db:setup

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
